### ISSUE TITLE
String matching in violation output is case sensitive

### ISSUE THREAD

**Issue by cjsauer** [audiobahn404/test_cs352#6]
Tiny issue. 

"type mismatch in expression" failed:
Expected: "Line 2, type violation"
Got: "line 2, type violation"

**Comment by faultyserver** [comment]
Going by the spec, all of the violations start with capital 'L's, so I think you'd be better off having your parser do the same.

Similarly, I doubt that this will actually come up, but ignoring the case of the output would make the harness incapable of testing string manipulations. Obviously, this isn't something we're doing (and likely won't ever do), but it's a future-compatibility kind of issue. For example, a test definition of:

``` lang-js
/* test_upper_case_function */
input: |+
  <script type="text/JavaScript">
    var x = "String";
    document.write(upper_case(x));
  </script>
output: |+
  STRING
```

would pass even if the `upper_case` function left the string as `String`.

Because of that, I would prefer keeping the harness case sensitive.

**Comment by cjsauer** [comment]
Ah good point. I didn't think of that.
